# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8722c609a14fcf691d514824425d0328f9227122af0c8243ec126d4b357bf42815223f0cd821d474a36872065895d7d4e88472b6e3c0657db2e7ba07af0da409

test:
  secret_key_base: 4b3922e83da84856f81c2648175b0287fba401239a8536c16628e9c96d89795c0ed432e10f8fb864e0e541e9d97943ae326e224717791914599eab13500cacc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
